name: gpu_noise
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: '>=2.1.4 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: '>=4.0.0 <5.0.0'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  shaders:
    - lib/src/shaders/cellular2.frag
    - lib/src/shaders/cellular2x2.frag
    - lib/src/shaders/cellular2x2x2.frag
    - lib/src/shaders/cellular3.frag
    - lib/src/shaders/curl2.frag
    - lib/src/shaders/curl3.frag
    - lib/src/shaders/curl4.frag
    - lib/src/shaders/fbm2.frag
    - lib/src/shaders/fbm3.frag
    - lib/src/shaders/gerstner_wave2.frag
    - lib/src/shaders/gradient2.frag
    - lib/src/shaders/gradient3.frag
    - lib/src/shaders/perlin2.frag
    - lib/src/shaders/perlin3.frag
    - lib/src/shaders/perlin4.frag
    - lib/src/shaders/psrd2.frag
    - lib/src/shaders/psrd3.frag
    - lib/src/shaders/random2.frag
    - lib/src/shaders/random3.frag
    - lib/src/shaders/random4.frag
    - lib/src/shaders/signed_random2.frag
    - lib/src/shaders/signed_random3.frag
    - lib/src/shaders/signed_random4.frag
    - lib/src/shaders/simplex2.frag
    - lib/src/shaders/simplex3.frag
    - lib/src/shaders/simplex4.frag
    - lib/src/shaders/tiling_fbm3.frag
    - lib/src/shaders/tiling_gradient3.frag
    - lib/src/shaders/tiling_perlin2.frag
    - lib/src/shaders/tiling_perlin3.frag
    - lib/src/shaders/tiling_perlin4.frag
    - lib/src/shaders/tiling_simplex2.frag
    - lib/src/shaders/tiling_simplex3.frag
    - lib/src/shaders/tiling_signed_random2.frag
    - lib/src/shaders/tiling_signed_random3.frag
    - lib/src/shaders/tiling_simplex2.frag
    - lib/src/shaders/tiling_simplex3.frag
    - lib/src/shaders/tiling_simplex_flow2.frag
    - lib/src/shaders/tiling_simplex_flow3.frag
    - lib/src/shaders/voronoi2.frag
    - lib/src/shaders/voronoi3.frag
    - lib/src/shaders/voronoi_time2.frag
    - lib/src/shaders/voronoise2.frag
    - lib/src/shaders/voronoise3.frag
    - lib/src/shaders/wavelet2.frag
    - lib/src/shaders/worley2.frag
    - lib/src/shaders/worley3.frag

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
